{{- if .Values.iam.enabled }}

apiVersion: iam.openfaas.com/v1
kind: Policy
metadata:
  name: root-user
  namespace: {{ .Release.Namespace | quote }}
spec:
  statement:
  - sid: 1-full-access-cluster
    action:
    - Function:*
    - Secret:*
    - Namespace:*
    - System:*
    effect: Allow
    resource: [ "*" ]

{{- end}}